apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository 
metadata: 
  name: myhelmrepo
  namespace: default
spec:
  interval: 5m0s # check repo for changes
  url: http://192.168.2.216:8080 # ifconfig.en0.inet / machine address
  secretRef:
    name: myhelmrepo-secret
—--
apiVersion: v1
kind: Secret
metadata:
  name: myhelmrepo-secret
  namespace: default
stringData:
  username: chartuser
  password: mypass
